### ISSUE TITLE
Atom Tutorials

### ISSUE THREAD

**Issue by eak24** [AguaClara/aguaclara_tutorial#2]
@kevinjuan25 [here's a video I made about cloning in Atom.](http://autode.sk/2DA1nlP) Turns out Atom does support cloning! yay!

**Comment by eak24** [comment]
@kevinjuan25 another thing to include is how to render Latex... hopefully in video form? You need to turn on Latex when using the preview in Atom. See the following screenshot:

<img width="806" alt="screen shot 2018-01-23 at 15 52 51" src="https://user-images.githubusercontent.com/8585379/35302886-bb5b5450-0055-11e8-84ce-6558726dc819.png">

**Comment by kevinjuan25** [comment]
@ethan92429 What would be useful for an interactive Hydrogen markdown file? Should I have code for people to run? Should I do it more like a question and answer thing where people write code to answer questions and run it in Hydrogen? I'll add a section about LaTeX rendering with a video.

**Comment by eak24** [comment]
I think you should take the tutorial you already have, add some Latex, and then make a video going through it, so people can see the process of cloning this wiki repo, opening it in Atom, running hydrogen on some cells, previewing the markdown, turning on Latex rendering, and finally sharing with your friend with teletype and then committing and pushing the code. Does that sound like too much? I use screencast by Autodesk because it records my keystrokes.

**Comment by kevinjuan25** [comment]
Sounds good! I'll probably break them down into videos for each topic so that people won't have to watch through the entire thing to find out how to use 1 thing. I'll probably do it in a mini-series style where the videos will be sequential (i.e. start from cloning and end with commit/push). How does that sound?

Also, I was thinking about making an interactive markdown file as a way for students to learn Python. What are your thoughts on that?

**Comment by kevinjuan25** [comment]
@ethan92429 @cc2467 Does LaTeX rendering show up only within markdown preview and not on say a GitHub wiki markdown?
